name: advanced_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  analyzer: ^5.7.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  get_it: ^7.2.0
  image_picker: ^0.8.7+5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  lottie: ^2.3.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/python_logo.png
    - assets/images/artificial-brain-computer-svgrepo-com.svg
    - assets/images/artificial-intelligence-svgrepo-com.svg
    - assets/images/bar-chart-sorted-business-analytics-statistics-svgrepo-com.svg
    - assets/images/donut-chart-piece-business-analytics-statistics-svgrepo-com.svg
    - assets/images/icons8-python.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/error-1.json
    - assets/json/error-2.json
    - assets/json/error-3.json
    - assets/json/empty.json
    - assets/json/empty-box.json
    - assets/json/success.json
    - assets/json/done.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
